frigg/builds/api.py
frigg/builds/migrations/0006_buildresult_coverage.py
frigg/builds/models.py
frigg/builds/test_api.py
frigg/helpers/badges.py
frigg/helpers/test_badges.py
frigg/urls.py

Add coverage badge support

---

frigg/builds/admin.py
frigg/builds/models.py
frigg/builds/templates/builds/build.html
frigg/builds/test_models.py

Add coverage and coverage diff to build details page

---

.frigg.yml
.isort.cfg
frigg/authentication/migrations/0001_initial.py
frigg/authentication/test_decorators.py
frigg/builds/management/commands/push_test_github_hook.py
frigg/builds/management/commands/restart_builds.py
frigg/builds/migrations/0001_initial.py
frigg/builds/migrations/0002_auto_20141028_0710.py
frigg/builds/migrations/0004_auto_20141114_1336.py
frigg/builds/migrations/0005_auto_20141120_1221.py
frigg/builds/migrations/0006_buildresult_coverage.py
frigg/builds/models.py
frigg/builds/test_api.py
frigg/builds/test_managers.py
frigg/builds/test_models.py
frigg/builds/test_views.py
frigg/builds/urls.py
frigg/builds/views.py
frigg/helpers/test_badges.py
frigg/helpers/test_common.py
frigg/helpers/test_github.py
frigg/settings/base.py
frigg/stats/test_views.py
frigg/stats/urls.py
frigg/stats/views.py
frigg/urls.py
frigg/utils/tests.py
frigg/webhooks/test_views.py
frigg/wsgi.py

This also fix all bad orderings. Fixing sorting can be done with
`isort -rc frigg`.

Add import ordering check in frigg settings

---

frigg/builds/migrations/0007_build_message.py
frigg/builds/models.py
frigg/builds/templates/builds/build.html
frigg/builds/templates/builds/partials/build_list_element.html
frigg/builds/test_models.py
frigg/files/sass/main.sass
frigg/helpers/fixtures/github/pull_request.json
frigg/helpers/github.py
frigg/helpers/test_github.py
frigg/webhooks/test_views.py

Fix #141, Add message to builds

---

frigg/builds/templates/builds/build.html

This polls the api and refresh when the build gets a result.
**Depends on #149**

Add temporary refresh of build page when build is finished

---

frigg/builds/urls.py
frigg/stats/urls.py
frigg/urls.py
frigg/webhooks/urls.py

Refactor urls, use lists instead of patterns()

---

frigg/api/fixtures/test_views.yaml
frigg/builds/admin.py
frigg/builds/fixtures/test_permitted_objects.yaml
frigg/builds/migrations/0012_remove_project_user.py
frigg/builds/models.py
frigg/builds/test_models.py
frigg/webhooks/views.py

Use first member for github authentication instead

Remove Project.user

---

frigg/helpers/badges.py

Add '%' in coverage badge

---

frigg/settings/base.py
requirements/base.txt

Add django-cachalot

---

frigg/api/views.py
frigg/builds/api.py
frigg/builds/filters.py
frigg/builds/managers.py
frigg/builds/models.py
frigg/builds/serializers.py
frigg/builds/test_api.py
frigg/builds/test_filters.py
frigg/builds/test_managers.py
frigg/builds/test_views.py
frigg/builds/urls.py
frigg/builds/views.py
frigg/projects/filters.py
frigg/projects/managers.py
frigg/projects/models.py
frigg/projects/serializers.py
frigg/projects/test_filters.py
frigg/projects/test_managers.py
frigg/projects/test_views.py
frigg/projects/urls.py
frigg/projects/views.py
frigg/urls.py
frigg/utils/tests.py

The model is still in builds because it needs db changes that need
planning.

Move projects to its own app

---

frigg/api/test_views.py
frigg/builds/migrations/0022_buildresult_setup_log.py
frigg/builds/models.py

This only adds the support in the API. There are no changes to the UI.
cc: @frecar

Add support for setup tasks in the report api

---

.frigg.yml

Change order of tasks in order to fail tests faster if flake or isort error

---

frigg/api/test_views.py
frigg/api/urls.py
frigg/api/views.py

Adds view for builds given owner, name and build number

---

.frigg.yml
frigg/api/test_views.py
frigg/api/urls.py
frigg/api/views.py
frigg/builds/migrations/0020_project_can_deploy.py
frigg/builds/migrations/0022_merge.py
frigg/builds/migrations/0023_merge.py
frigg/builds/models.py
frigg/builds/templates/builds/partials/build_result.html
frigg/deployments/admin.py
frigg/deployments/managers.py
frigg/deployments/migrations/0001_initial.py
frigg/deployments/models.py
frigg/deployments/serializers.py
frigg/deployments/test_managers.py
frigg/deployments/test_models.py
frigg/settings/base.py

This is only db stuff and report API for initial tryout of deployment worker(in other words no other frontend than django admin).

Add management of PRDeployments

---

frigg/builds/admin.py
frigg/builds/migrations/0025_buildresult_worker_host.py
frigg/builds/models.py
frigg/builds/test_models.py

Add worker host from build results (fixes #236)

---

frigg/builds/models.py
frigg/builds/test_models.py
frigg/deployments/migrations/0004_auto_20150725_1456.py
frigg/deployments/models.py
frigg/deployments/test_managers.py
frigg/settings/frigg.py

Add default preview image as an setting (closes #246)

---

frigg/webhooks/events/base.py

Build valid BuildResult with json

---

frigg/settings/base.py
frigg/workers/admin.py
frigg/workers/migrations/0001_initial.py
frigg/workers/models.py

add workers model

---

.frigg.yml
tox.ini

Change from python3.4 to python3 (tox)

---

frigg/builds/models.py
frigg/builds/test_models.py
frigg/helpers/badges.py

fix(badges): Return unknown badges for unknown things
